# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_nuc_div_theta <- function(dna_matrix, pairwise_deletion = TRUE, model = "raw") {
    .Call(`_gSoup_calc_nuc_div_theta`, dna_matrix, pairwise_deletion, model)
}

calculate_pi <- function(alignment) {
    .Call(`_gSoup_calculate_pi`, alignment)
}

calculate_sfs_cpp <- function(alignment) {
    .Call(`_gSoup_calculate_sfs_cpp`, alignment)
}

